# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
job:
 steps:
 - run:   echo ::set-env name=GHA_COUNTER::$(grep "kill" awesomeNewFile.txt | wc -l)
   shell: bash
 - run: echo "There's a thing in my code!"
   if:  env.GHA_COUNTER == '0'
